// Frame definitions with rich visual properties
// Each frame is rendered on canvas with special effects

export interface FrameDef {
  id: string;
  name: string;
  emoji: string;
  category: "classic" | "korean" | "elegant" | "fun" | "dark";
  // Corner colors for gradient interpolation (Korean glitter style)
  cornerColors: { tl: string; tr: string; bl: string; br: string };
  // Label area
  labelBg: string;
  labelText: string;
  // Sizing
  borderWidth: number;
  borderRadius: number;
  innerRadius: number;
  gap: number; // gap between photos in strip/grid
  // Font
  fontFamily: string;
  // Effects
  hasGlitter: boolean;
  hasSparkles: boolean;
  hasSprockets: boolean; // film strip holes
  hasInnerShadow: boolean;
  // Optional solid/gradient override (if not using corner interpolation)
  solidColor?: string;
  patternType?: "none" | "dots" | "hearts" | "stars" | "stripes";
}

export const FRAMES: FrameDef[] = [
  // ===== CLASSIC =====
  {
    id: "classic-white",
    name: "Classic White",
    emoji: "⬜",
    category: "classic",
    cornerColors: { tl: "#ffffff", tr: "#ffffff", bl: "#ffffff", br: "#ffffff" },
    labelBg: "#ffffff",
    labelText: "#333333",
    borderWidth: 36,
    borderRadius: 4,
    innerRadius: 2,
    gap: 10,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#ffffff",
  },
  {
    id: "polaroid-cream",
    name: "Polaroid",
    emoji: "📷",
    category: "classic",
    cornerColors: { tl: "#faf8f0", tr: "#f5f0e0", bl: "#f0ead0", br: "#ede5c8" },
    labelBg: "#faf8f0",
    labelText: "#5a5040",
    borderWidth: 30,
    borderRadius: 4,
    innerRadius: 0,
    gap: 0,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#faf8f0",
  },

  // ===== KOREAN =====
  {
    id: "korean-pink",
    name: "Pink Dream",
    emoji: "🌸",
    category: "korean",
    cornerColors: { tl: "#ffb6c1", tr: "#ff69b4", bl: "#dda0dd", br: "#ff1493" },
    labelBg: "#fff0f5",
    labelText: "#c71585",
    borderWidth: 32,
    borderRadius: 12,
    innerRadius: 8,
    gap: 10,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
  },
  {
    id: "korean-blue",
    name: "Ocean Sky",
    emoji: "🌊",
    category: "korean",
    cornerColors: { tl: "#87ceeb", tr: "#4169e1", bl: "#00bfff", br: "#1e90ff" },
    labelBg: "#f0f8ff",
    labelText: "#1e3a5f",
    borderWidth: 32,
    borderRadius: 12,
    innerRadius: 8,
    gap: 10,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
  },
  {
    id: "korean-lavender",
    name: "Lavender",
    emoji: "💜",
    category: "korean",
    cornerColors: { tl: "#e6e6fa", tr: "#d8bfd8", bl: "#dda0dd", br: "#ba55d3" },
    labelBg: "#f5f0ff",
    labelText: "#6a0dad",
    borderWidth: 32,
    borderRadius: 12,
    innerRadius: 8,
    gap: 10,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
  },
  {
    id: "korean-mint",
    name: "Mint Fresh",
    emoji: "🍃",
    category: "korean",
    cornerColors: { tl: "#98fb98", tr: "#00fa9a", bl: "#7fffd4", br: "#3cb371" },
    labelBg: "#f0fff0",
    labelText: "#2e8b57",
    borderWidth: 32,
    borderRadius: 12,
    innerRadius: 8,
    gap: 10,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
  },

  // ===== ELEGANT =====
  {
    id: "wedding-gold",
    name: "Wedding Gold",
    emoji: "💍",
    category: "elegant",
    cornerColors: { tl: "#d4af37", tr: "#ffd700", bl: "#b8860b", br: "#daa520" },
    labelBg: "#1a1a2e",
    labelText: "#d4af37",
    borderWidth: 28,
    borderRadius: 8,
    innerRadius: 4,
    gap: 10,
    fontFamily: "'Georgia', serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    emoji: "🌹",
    category: "elegant",
    cornerColors: { tl: "#e8b4b8", tr: "#d4a0a0", bl: "#c48888", br: "#b07070" },
    labelBg: "#2d1f1f",
    labelText: "#e8b4b8",
    borderWidth: 28,
    borderRadius: 8,
    innerRadius: 4,
    gap: 10,
    fontFamily: "'Georgia', serif",
    hasGlitter: true,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
  },

  // ===== FUN =====
  {
    id: "rainbow-party",
    name: "Rainbow",
    emoji: "🌈",
    category: "fun",
    cornerColors: { tl: "#ff6b6b", tr: "#feca57", bl: "#48dbfb", br: "#ff9ff3" },
    labelBg: "#ffffff",
    labelText: "#333333",
    borderWidth: 32,
    borderRadius: 16,
    innerRadius: 10,
    gap: 10,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    patternType: "stars",
  },
  {
    id: "hearts-cute",
    name: "Love Cute",
    emoji: "💖",
    category: "fun",
    cornerColors: { tl: "#ff69b4", tr: "#ff1493", bl: "#ff6eb4", br: "#ff149e" },
    labelBg: "#fff0f5",
    labelText: "#c71585",
    borderWidth: 32,
    borderRadius: 16,
    innerRadius: 10,
    gap: 10,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    patternType: "hearts",
  },

  // ===== DARK =====
  {
    id: "film-noir",
    name: "Film Noir",
    emoji: "🎬",
    category: "dark",
    cornerColors: { tl: "#1a1a1a", tr: "#1a1a1a", bl: "#1a1a1a", br: "#1a1a1a" },
    labelBg: "#1a1a1a",
    labelText: "#ff4444",
    borderWidth: 36,
    borderRadius: 0,
    innerRadius: 0,
    gap: 12,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: true,
    hasInnerShadow: false,
    solidColor: "#1a1a1a",
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    emoji: "⚡",
    category: "dark",
    cornerColors: { tl: "#00ff88", tr: "#00ccff", bl: "#ff00ff", br: "#ffff00" },
    labelBg: "#0a0a0a",
    labelText: "#00ff88",
    borderWidth: 28,
    borderRadius: 12,
    innerRadius: 8,
    gap: 10,
    fontFamily: "'Courier New', monospace",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
  },
  {
    id: "midnight-blue",
    name: "Midnight",
    emoji: "🌙",
    category: "dark",
    cornerColors: { tl: "#0c1445", tr: "#1a237e", bl: "#0d47a1", br: "#1565c0" },
    labelBg: "#0c1445",
    labelText: "#90caf9",
    borderWidth: 28,
    borderRadius: 8,
    innerRadius: 4,
    gap: 10,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#0c1445",
  },
];

export const FRAME_CATEGORIES = [
  { id: "all", name: "Semua", emoji: "✨" },
  { id: "classic", name: "Classic", emoji: "📷" },
  { id: "korean", name: "Korean", emoji: "🇰🇷" },
  { id: "elegant", name: "Elegant", emoji: "💎" },
  { id: "fun", name: "Fun", emoji: "🎉" },
  { id: "dark", name: "Dark", emoji: "🌙" },
] as const;
