// Frame definitions with rich visual properties
// Each frame is rendered on canvas with special effects and fixed-proportions photobooth strip slots

export type FrameShapeStyle = "classic" | "arch" | "washi-tape" | "stamp" | "wave" | "collage-tilt";
export type MusicBandTheme =
  | "the1975"
  | "multo"
  | "wavetoearth"
  | "newjeans"
  | "arcticmonkeys"
  | "taylorswift"
  | "sza"
  | "frankocean";

export interface FrameDef {
  id: string;
  name: string;
  emoji: string;
  category: "music" | "classic" | "korean" | "y2k" | "film" | "cute" | "minimal" | "dark" | "artistic";
  shapeStyle?: FrameShapeStyle; // Bentuk Seni: arch, washi tape, stamp, wave, collage-tilt
  musicTheme?: MusicBandTheme; // Otomatisasi style logo/gambar band & album hits
  cornerColors: { tl: string; tr: string; bl: string; br: string };
  labelBg: string;
  labelText: string;
  borderWidth: number;
  borderRadius: number;
  innerRadius: number;
  gap: number;
  fontFamily: string;
  hasGlitter: boolean;
  hasSparkles: boolean;
  hasSprockets: boolean; // 35mm film strip holes
  hasInnerShadow: boolean;
  solidColor?: string;
  patternType?: "none" | "dots" | "hearts" | "stars" | "stripes" | "checkered";
  accentColor?: string;
  tagline?: string;
  washiColor?: string;
}

export const FRAMES: FrameDef[] = [
  // ===== HIT ALBUMS & BANDS (THE 1975, MULTO, NEWJEANS, ETC.) =====
  {
    id: "frame-the1975",
    name: "The 1975: About You",
    emoji: "🖤",
    category: "music",
    musicTheme: "the1975",
    cornerColors: { tl: "#09090b", tr: "#18181b", bl: "#09090b", br: "#27272a" },
    solidColor: "#101012",
    labelBg: "#1c1c20",
    labelText: "#ffffff",
    borderWidth: 32,
    borderRadius: 16,
    innerRadius: 10,
    gap: 14,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "The 1975 // About You",
  },
  {
    id: "frame-multo",
    name: "Multo: Cup of Joe",
    emoji: "🥀",
    category: "music",
    musicTheme: "multo",
    cornerColors: { tl: "#2e0814", tr: "#4c0519", bl: "#1c040b", br: "#3a0916" },
    labelBg: "#3b0716",
    labelText: "#fed7aa",
    borderWidth: 30,
    borderRadius: 18,
    innerRadius: 12,
    gap: 14,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "Kahit Sa Panaginip Lang // Multo",
  },
  {
    id: "frame-wavetoearth",
    name: "wave to earth: seasons",
    emoji: "🌊",
    category: "music",
    musicTheme: "wavetoearth",
    cornerColors: { tl: "#081b29", tr: "#0f3750", bl: "#05111a", br: "#154c6e" },
    labelBg: "#0c273d",
    labelText: "#7dd3fc",
    borderWidth: 30,
    borderRadius: 18,
    innerRadius: 12,
    gap: 14,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "wave to earth // seasons",
  },
  {
    id: "frame-newjeans",
    name: "NewJeans: Ditto Bunny",
    emoji: "🐰",
    category: "music",
    musicTheme: "newjeans",
    cornerColors: { tl: "#2563eb", tr: "#7c3aed", bl: "#0284c7", br: "#c084fc" },
    labelBg: "#1e1b4b",
    labelText: "#ffffff",
    borderWidth: 30,
    borderRadius: 20,
    innerRadius: 12,
    gap: 12,
    fontFamily: "'Courier New', monospace",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Stay in the middle // Ditto",
  },
  {
    id: "frame-arcticmonkeys",
    name: "Arctic Monkeys: 505 / AM",
    emoji: "🎸",
    category: "music",
    musicTheme: "arcticmonkeys",
    cornerColors: { tl: "#09090b", tr: "#18181b", bl: "#050507", br: "#27272a" },
    solidColor: "#0a0a0c",
    labelBg: "#18181b",
    labelText: "#f43f5e",
    borderWidth: 32,
    borderRadius: 16,
    innerRadius: 10,
    gap: 14,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "AM Frequency // 505",
  },
  {
    id: "frame-taylorswift",
    name: "Taylor Swift: Lover Pink",
    emoji: "💖",
    category: "music",
    musicTheme: "taylorswift",
    cornerColors: { tl: "#f472b6", tr: "#c084fc", bl: "#fbcfe8", br: "#93c5fd" },
    labelBg: "#fdf2f8",
    labelText: "#be185d",
    borderWidth: 32,
    borderRadius: 22,
    innerRadius: 14,
    gap: 12,
    fontFamily: "'Georgia', serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Can I Go Where You Go? // Lover",
  },
  {
    id: "frame-sza",
    name: "SZA: SOS / Snooze",
    emoji: "🌙",
    category: "music",
    musicTheme: "sza",
    cornerColors: { tl: "#020617", tr: "#1e3a8a", bl: "#0b1329", br: "#1d4ed8" },
    labelBg: "#0a1128",
    labelText: "#fde047",
    borderWidth: 30,
    borderRadius: 18,
    innerRadius: 12,
    gap: 14,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "I Can't Lose With You // S.O.S",
  },
  {
    id: "frame-frankocean",
    name: "Frank Ocean: Blonde / Orange",
    emoji: "🍊",
    category: "music",
    musicTheme: "frankocean",
    cornerColors: { tl: "#c2410c", tr: "#d97706", bl: "#9a3412", br: "#b45309" },
    labelBg: "#431407",
    labelText: "#fed7aa",
    borderWidth: 32,
    borderRadius: 14,
    innerRadius: 8,
    gap: 12,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "Blonded // Pink + White",
  },
  // ===== KOREAN VIBES =====
  {
    id: "korean-blossom",
    name: "Blossom Pink",
    emoji: "🌸",
    category: "korean",
    cornerColors: { tl: "#ffe5ec", tr: "#ffc2d1", bl: "#ffb3c6", br: "#ff8fab" },
    labelBg: "#fff0f3",
    labelText: "#c9184a",
    borderWidth: 28,
    borderRadius: 20,
    innerRadius: 14,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Life4Cuts Pink Dream",
  },
  {
    id: "korean-lilac",
    name: "Lilac Cloud",
    emoji: "💜",
    category: "korean",
    cornerColors: { tl: "#ede7f6", tr: "#d1c4e9", bl: "#b39ddb", br: "#9575cd" },
    labelBg: "#f3e5f5",
    labelText: "#5e35b1",
    borderWidth: 28,
    borderRadius: 20,
    innerRadius: 14,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Haru Film Aesthetic",
  },
  {
    id: "korean-sky",
    name: "Sky Blue Breeze",
    emoji: "☁️",
    category: "korean",
    cornerColors: { tl: "#e1f5fe", tr: "#b3e5fc", bl: "#81d4fa", br: "#4fc3f7" },
    labelBg: "#e0f7fa",
    labelText: "#0277bd",
    borderWidth: 28,
    borderRadius: 20,
    innerRadius: 14,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Photoism Cool Sky",
  },
  {
    id: "korean-matcha",
    name: "Matcha Latte",
    emoji: "🍵",
    category: "korean",
    cornerColors: { tl: "#f1f8e9", tr: "#dcedc8", bl: "#c5e1a5", br: "#aed581" },
    labelBg: "#f9fbe7",
    labelText: "#33691e",
    borderWidth: 28,
    borderRadius: 20,
    innerRadius: 14,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Cozy Café Seoul",
  },
  {
    id: "korean-butter-peach",
    name: "Butter Peach",
    emoji: "🍑",
    category: "korean",
    cornerColors: { tl: "#fff3e0", tr: "#ffe0b2", bl: "#ffcc80", br: "#ffb74d" },
    labelBg: "#fff8e1",
    labelText: "#e65100",
    borderWidth: 28,
    borderRadius: 20,
    innerRadius: 14,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Sunset Warmth",
  },

  // ===== Y2K & CYBER =====
  {
    id: "y2k-cyber",
    name: "Y2K Cyberpunk",
    emoji: "💿",
    category: "y2k",
    cornerColors: { tl: "#0d0221", tr: "#0f084b", bl: "#26408b", br: "#00ffff" },
    labelBg: "#050014",
    labelText: "#00ffff",
    borderWidth: 32,
    borderRadius: 16,
    innerRadius: 10,
    gap: 14,
    fontFamily: "'Courier New', monospace",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    solidColor: "#0a0a14",
    tagline: "Retro Cyber Matrix",
  },
  {
    id: "checkered-pink",
    name: "Pink Checker Y2K",
    emoji: "🏁",
    category: "y2k",
    cornerColors: { tl: "#ff69b4", tr: "#ffffff", bl: "#ff69b4", br: "#ffffff" },
    labelBg: "#ff69b4",
    labelText: "#ffffff",
    borderWidth: 32,
    borderRadius: 18,
    innerRadius: 10,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    patternType: "checkered",
    tagline: "Pop Punk Checker",
  },
  {
    id: "y2k-silver-holo",
    name: "Silver Hologram",
    emoji: "✨",
    category: "y2k",
    cornerColors: { tl: "#e0e0e0", tr: "#f5f5f5", bl: "#d6d6d6", br: "#c4c4c4" },
    labelBg: "#ebebeb",
    labelText: "#424242",
    borderWidth: 30,
    borderRadius: 16,
    innerRadius: 8,
    gap: 12,
    fontFamily: "'Courier New', monospace",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
    tagline: "Futuristic CD Shine",
  },

  // ===== VINTAGE & FILM =====
  {
    id: "film-sprocket-noir",
    name: "Kodak 35mm Sprocket",
    emoji: "🎞️",
    category: "film",
    cornerColors: { tl: "#1a1a1a", tr: "#1a1a1a", bl: "#1a1a1a", br: "#1a1a1a" },
    labelBg: "#121212",
    labelText: "#f5a623",
    borderWidth: 42,
    borderRadius: 0,
    innerRadius: 0,
    gap: 14,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: true,
    hasInnerShadow: false,
    solidColor: "#181818",
    tagline: "True 35mm Roll Film",
  },
  {
    id: "polaroid-warm",
    name: "Vintage Polaroid",
    emoji: "📷",
    category: "film",
    cornerColors: { tl: "#faf7ee", tr: "#f6f1e3", bl: "#f0ebd8", br: "#eae3cb" },
    labelBg: "#faf7ee",
    labelText: "#5c4f3d",
    borderWidth: 32,
    borderRadius: 4,
    innerRadius: 2,
    gap: 12,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#faf7ee",
    tagline: "Original 70s Instant",
  },
  {
    id: "retro-sepia-film",
    name: "Retro Sepia 1985",
    emoji: "☕",
    category: "film",
    cornerColors: { tl: "#e8d5c4", tr: "#dfc7b2", bl: "#d5b99f", br: "#caaa8d" },
    labelBg: "#f2e4d7",
    labelText: "#4e3629",
    borderWidth: 30,
    borderRadius: 6,
    innerRadius: 4,
    gap: 10,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#e8d5c4",
    tagline: "Nostalgic Warmth",
  },

  // ===== CUTE & PLAYFUL =====
  {
    id: "cute-strawberry",
    name: "Sweet Berry",
    emoji: "🍓",
    category: "cute",
    cornerColors: { tl: "#ff758c", tr: "#ff7eb3", bl: "#ffb199", br: "#ff0844" },
    labelBg: "#fff1f3",
    labelText: "#d90429",
    borderWidth: 30,
    borderRadius: 24,
    innerRadius: 16,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Juicy Kawaii Pop",
  },
  {
    id: "cute-starry-galaxy",
    name: "Starry Twilight",
    emoji: "⭐",
    category: "cute",
    cornerColors: { tl: "#3a1c71", tr: "#d76d77", bl: "#ffaf7b", br: "#654ea3" },
    labelBg: "#231341",
    labelText: "#ffd166",
    borderWidth: 30,
    borderRadius: 20,
    innerRadius: 12,
    gap: 12,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Dreamy Magic Star",
  },
  {
    id: "cute-scrapbook",
    name: "Cute Scrapbook",
    emoji: "📓",
    category: "cute",
    cornerColors: { tl: "#fdfbf7", tr: "#fdfbf7", bl: "#fdfbf7", br: "#fdfbf7" },
    labelBg: "#fdfbf7",
    labelText: "#7b2cbf",
    borderWidth: 38,
    borderRadius: 8,
    innerRadius: 4,
    gap: 16,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    patternType: "dots",
    solidColor: "#fdfbf7",
    tagline: "Washi Tape Journal",
  },

  // ===== MINIMAL & CLASSIC =====
  {
    id: "classic-white",
    name: "Classic Studio White",
    emoji: "⬜",
    category: "minimal",
    cornerColors: { tl: "#ffffff", tr: "#ffffff", bl: "#ffffff", br: "#ffffff" },
    labelBg: "#ffffff",
    labelText: "#1f2937",
    borderWidth: 32,
    borderRadius: 8,
    innerRadius: 4,
    gap: 10,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#ffffff",
    tagline: "Clean & Timeless",
  },
  {
    id: "minimal-monochrome-black",
    name: "Midnight Noir",
    emoji: "🖤",
    category: "minimal",
    cornerColors: { tl: "#111827", tr: "#111827", bl: "#111827", br: "#111827" },
    labelBg: "#0f172a",
    labelText: "#f9fafb",
    borderWidth: 32,
    borderRadius: 8,
    innerRadius: 4,
    gap: 10,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#111827",
    tagline: "High Fashion Monochrome",
  },
  {
    id: "wedding-champagne-gold",
    name: "Champagne Luxury",
    emoji: "🥂",
    category: "minimal",
    cornerColors: { tl: "#fbf8f2", tr: "#f4ede0", bl: "#ebdcc5", br: "#dfc79b" },
    labelBg: "#fbf8f2",
    labelText: "#8b6f38",
    borderWidth: 30,
    borderRadius: 10,
    innerRadius: 6,
    gap: 12,
    fontFamily: "'Georgia', serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#f7f1e5",
    tagline: "Wedding & Celebration",
  },
  // ===== ARTISTIC & UNIQUE SHAPES =====
  {
    id: "seoul-arch-dome",
    name: "Seoul Cathedral Arch",
    emoji: "🏛️",
    category: "artistic",
    shapeStyle: "arch",
    cornerColors: { tl: "#fdfbf7", tr: "#fcf6ed", bl: "#faeedb", br: "#f7e5c8" },
    labelBg: "#f5e6ce",
    labelText: "#78350f",
    borderWidth: 32,
    borderRadius: 24,
    innerRadius: 18,
    gap: 16,
    fontFamily: "'Georgia', serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    solidColor: "#faf5ef",
    tagline: "Kubah Lengkung Artistik",
  },
  {
    id: "artistic-arch-lilac",
    name: "Lilac Gallery Dome",
    emoji: "💜",
    category: "artistic",
    shapeStyle: "arch",
    cornerColors: { tl: "#f5f3ff", tr: "#ede9fe", bl: "#ddd6fe", br: "#c4b5fd" },
    labelBg: "#f3e8ff",
    labelText: "#581c87",
    borderWidth: 32,
    borderRadius: 24,
    innerRadius: 18,
    gap: 16,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Kubah Seni Seoul Ungu",
  },
  {
    id: "scrapbook-washi-tape",
    name: "Washi Tape Scrapbook",
    emoji: "📎",
    category: "artistic",
    shapeStyle: "washi-tape",
    cornerColors: { tl: "#fffbf0", tr: "#fff7e6", bl: "#fff1d6", br: "#ffe8be" },
    labelBg: "#ffedd5",
    labelText: "#9a3412",
    borderWidth: 34,
    borderRadius: 16,
    innerRadius: 8,
    gap: 18,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#fffbf2",
    tagline: "Kolase Selotip Scrapbook",
    washiColor: "#f472b6",
  },
  {
    id: "vintage-postage-stamp",
    name: "Art Postage Stamp",
    emoji: "📮",
    category: "artistic",
    shapeStyle: "stamp",
    cornerColors: { tl: "#f8fafc", tr: "#f1f5f9", bl: "#e2e8f0", br: "#cbd5e1" },
    labelBg: "#e2e8f0",
    labelText: "#334155",
    borderWidth: 36,
    borderRadius: 8,
    innerRadius: 6,
    gap: 16,
    fontFamily: "'Courier New', monospace",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#f8fafc",
    tagline: "Perangko Seni Perforasi",
  },
  {
    id: "wavy-pastel-ribbon",
    name: "Wavy Organic Ribbon",
    emoji: "〰️",
    category: "artistic",
    shapeStyle: "wave",
    cornerColors: { tl: "#fce7f3", tr: "#fbcfe8", bl: "#f472b6", br: "#db2777" },
    labelBg: "#fdf2f8",
    labelText: "#be185d",
    borderWidth: 34,
    borderRadius: 24,
    innerRadius: 16,
    gap: 14,
    fontFamily: "'Nunito', sans-serif",
    hasGlitter: true,
    hasSparkles: true,
    hasSprockets: false,
    hasInnerShadow: false,
    tagline: "Tepi Gelombang Estetik",
  },
  {
    id: "polaroid-tilted-collage",
    name: "Tilted Art Collage",
    emoji: "🎨",
    category: "artistic",
    shapeStyle: "collage-tilt",
    cornerColors: { tl: "#fafafa", tr: "#f4f4f5", bl: "#e4e4e7", br: "#d4d4d8" },
    labelBg: "#f4f4f5",
    labelText: "#18181b",
    borderWidth: 36,
    borderRadius: 14,
    innerRadius: 6,
    gap: 18,
    fontFamily: "'Georgia', serif",
    hasGlitter: false,
    hasSparkles: false,
    hasSprockets: false,
    hasInnerShadow: true,
    solidColor: "#ffffff",
    tagline: "Kolase Seni Miring Polaroid",
  },
];

export const FRAME_CATEGORIES = [
  { id: "all", name: "Semua Frame", emoji: "✨" },
  { id: "music", name: "Lagu & Band Hits", emoji: "🎵" },
  { id: "artistic", name: "Bentuk Seni & Unik", emoji: "🎨" },
  { id: "korean", name: "Korean 4-Cut", emoji: "🇰🇷" },
  { id: "y2k", name: "Y2K & Cyber", emoji: "💿" },
  { id: "film", name: "Vintage Film", emoji: "🎞️" },
  { id: "cute", name: "Cute Kawaii", emoji: "🎀" },
  { id: "minimal", name: "Minimal & Noir", emoji: "🤍" },
] as const;
